# ==================================================
#                   ПЕРМИШОНЫ
# ==================================================
#
# playerreporthelper.send
# Позволяет игроку отправлять репорты
# сейчас работает для всех игроков
#
# playerreporthelper.notify
# Получать сообщение о том что есть новый репорт
# ДЛЯ МОДЕРАТОРОВ!
#
# playerreporthelper.permission
# Доступ к GUI управления репортами
# Команда: /reports, /reports list
# ДЛЯ МОДЕРАТОРОВ!
#
# playerreporthelper.statsmoderator
# Доступ к статистике модераторов
# Команда: /reports stats
# Для модераторов/администраторов
#
# playerreporthelper.reload
# Перезагрузка конфигурации плагина
# Команда: /reports reload
# Для тех.админов/овнеров
#
# ==================================================


# =====================================================
# ⏱ РЕПОРТ КУЛДАУН
# =====================================================
# Время ожидания между отправкой репортов
# в секундах

cooldown-seconds: 30

# =====================================================
# ⏱ АВТО УДАЛЕНИЕ - РЕПОРТОВ
# =====================================================
# Время удаление репортов из гуи меню /reports list
# в ДНЯХ!
reports-cleanup-days: 3


# =====================================================
# 🔨 НАСТРОЙКИ НАКАЗАНИЯ
# =====================================================

ban:
  # Выполнять ли команду бана при ПРИНЯТИИ репорта
  enabled: true

  # Команда бана (%target% - ник нарушителя, %reason% - причина из репорта, %moderator% - ник модератора)
  # Пример:
  # "ban %target% %reason%" (дефолтный бан)
  command: "ban %target% %reason%"


# =====================================================
# 🖥 ГУИ МЕНЮ
# =====================================================

menus:

  # 📂 Открытые репорты
  reports-open:
    title: "&aОткрытые репорты &7| Страница %page%"
    size: 54

  # 📁 Закрытые репорты
  reports-closed:
    title: "&6Закрытые репорты &7| Страница %page%"
    size: 54

  # ⭐ Репутация игрока
  reputation:
    title: "&c⭐ Репутация игрока"
    size: 27

  # 📊 Статистика модератора
  stats:
    title: "&bСтатистика модератора"
    size: 27



# =====================================================
# 🧱 ГУИ ПРЕДМЕТЫ
# =====================================================

items:

  # 🔵 Заполнитель GUI
  filler:
    material: "BLUE_STAINED_GLASS_PANE"
    name: " "
    lore: []



  # ⭐ Материал репутации (сейчас это голова игрока) + настройка
  reputation-item:
    material: "PLAYER_HEAD"
    slot: 13
    name: "&c⭐ %player%"
    lore:
      - "&7Репутация игрока:"
      - "&6%points% ⭐"



  # 📊 Материал Статистики модератора (сейчас это голова игрока) + настройка
  stats-item:
    material: "PLAYER_HEAD"
    slot: 13
    name: "&b%player%"
    lore:
      - "&7Принято репортов: &a%accepted%"
      - "&7Отклонено репортов: &c%denied%"
      - "&7Среднее время ответа: &e%time% сек"



  # 🚨 Открытый репорт
  report-item-open:
    material: "PLAYER_HEAD"
    name: "&eРепорт на %target%"
    lore:
      - "&7Причина: &f%reason%"
      - "&7От игрока: &b%reporter%"
      - "&7Дата: &f%date%"
      - "&7ID: &e%id%"
      - "&7Статус: %status%"
      - ""
      - "&a✔ ЛКМ - принять"
      - "&c✖ ПКМ - отклонить"
      - "&b✦ SHIFT + ЛКМ - телепорт"



  # 📁 Закрытый репорт
  report-item-closed:
    material: "PLAYER_HEAD"
    name: "&e%target%"
    lore:
      - "&7Причина: &f%reason%"
      - "&7От: &b%reporter%"
      - "&7Дата: &f%date%"
      - "&7ID: &e%id%"
      - "&7Статус: %status%"
      - ""
      - "&7Модератор: &a%moderator%"
      - "&7Дата обработки: &f%handled_date%"
      - "&7Время ответа: &e%response_time% сек"



  # ➡ Следующая страница
  next-page:
    material: "ARROW"
    slot: 50
    name: "&e➡ Следующая страница"



  # ⬅ Предыдущая страница
  previous-page:
    material: "ARROW"
    slot: 48
    name: "&e⬅ Предыдущая страница"



# =====================================================
# 🔊 ЗВУКИ
# =====================================================

sounds:

  enabled: true

  # Нажатие на стекло
  click-glass: UI_BUTTON_CLICK

  # Нажатие на голову
  click-head: ENTITY_EXPERIENCE_ORB_PICKUP

  # Принятие репорта
  accept: ENTITY_PLAYER_LEVELUP

  # Отклонение репорта
  deny: ENTITY_VILLAGER_HURT



# =====================================================
# 💬 СООБЩЕНИЯ
# =====================================================

messages:

  no-permission: "&c❌ У вас нет прав."
  report-sent: "&a✔ Репорт успешно отправлен!"
  cooldown: "&c⏳ Подождите %seconds% сек."
  usage: "&7Использование: &f/report <ник> <причина>"
  player-offline: "&c❌ Игрок не в сети."
  teleported: "&a✔ Вы телепортированы к &e%player%"
  new-report: "&c⚠ Новый репорт на &f%target%"
  cannot-report-yourself: "&c❌ Вы не можете отправить репорт на самого себя."
  report-accepted: "&a&l[Репорты] &fВаша жалоба на игрока &e%target% &fбыла &aпринята&f модератором &b%moderator%&f!"
  report-denied: "&c&l[Репорты] &fВаша жалоба на игрока &e%target% &fбыла &cотклонена&f модератором &b%moderator%&f."



# =====================================================
# 🚫 BLACKLIST
# =====================================================
# Игроков с этими правами нельзя репортить

blacklist:
  - Notch



# =====================================================
# 🌐 DISCORD WEBHOOK
# =====================================================

webhook:

  enabled: false

  # Ссылка webhook Discord
  url: "https://discord.com/api/webhooks/PASTE_YOUR_WEBHOOK"

  # Имя бота
  username: "PlayerReportHelper"

  # Аватар бота
  avatar-url: "https://i.imgur.com/abc123.png"



  # Сообщения webhook
  messages:

    new-report:
      - "🚨 **Новый репорт**"
      - "👤 Игрок: **%target%**"
      - "📝 Репортёр: **%reporter%**"
      - "📄 Причина: **%reason%**"

    handled-report:
      - "📌 **Репорт обработан**"
      - "🆔 ID: **#%id%**"
      - "📊 Статус: **%status%**"
      - "👮 Модератор: **%moderator%**"